### ISSUE TITLE
WorldGuard-Towny NoClassDefFoundError on server start.

### ISSUE THREAD

**Issue by ConnorNMoran** [TownyAdvanced/WorldGuard-Towny#2]
**Describe the bug**
I'm getting this error when my server starts. I'm unsure what's causing it, I'm having other issues with Towny too so I would like to fix this so I can make sure it isn't a factor in any other errors.
My server is a hybrid plugin-modded server using the 1.12.2 pack, using Mohist to run.
I'm using Minecraft version 1.12.2,
Towny version 0.96.2,
WorldGuard version 6.2.2,
and WorldGuard-Towny version 1.1.0.

`
[08:07:54 ERROR]: com/sk89q/worldguard/WorldGuard initializing WorldGuard-Towny v1.1.0 (Is it up to date?)
 java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
    at WorldGuardTowny.onLoad(WorldGuardTowny.java:26) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:397) [CraftServer.class:?]
    at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:342) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:319) [nz.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:593) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:114) ~[PluginClassLoader.class:?]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[PluginClassLoader.class:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_265]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_265]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:112) ~[PluginClassLoader.class:?]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[PluginClassLoader.class:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
    ... 6 more
`

I've seen a thread talking about a similar error, but the cause was different, and so I'm unsure how to implement the solution so it would work?
[https://www.spigotmc.org/threads/worldguardapi-wolrdguard-noclassdeffounderror.380376/](url)

**To Reproduce**
1. Start the server.

**Expected behavior**
No error to occur.

**Comment by LlmDl** [comment]
Show me your full servers startup from the latest.log.

**Comment by ConnorNMoran** [comment]
https://pastebin.com/1ujT3fqZ

**Comment by LlmDl** [comment]
The version of WorldGuard for 1.12 does not have the WG class required by Worldguard-Towny. You will not be able to use WorldGuard-Towny on your server.

**Comment by ConnorNMoran** [comment]
Fair enough. Will Towny and WorldGuard conflict then?

**Comment by LlmDl** [comment]
Yes you should make NPC towns where you have to have WG regions.

**Comment by ConnorNMoran** [comment]
Ah, well thanks for the advice.
As a final question then, if I was to forgo using WorldGuard in favour of using Towny, (I like the hierarchy system) do you think that would be sufficient protection?
I also use LuckPerms and such so.

**Comment by ConnorNMoran** [comment]
Or going a different route, is there anyone I could hire to make a version of this that'll work for me?

That's also something I'm more than happy to do, since Towny is an excellent plugin anyways.

**Comment by LlmDl** [comment]
There's no need to use WG at all if you have Towny. An admin town can protect the spawn just as well as a WG region does.

If you want to hire a dev there's a whole slew of them on the Towny discord.

**Comment by ConnorNMoran** [comment]
Great to know thanks!
